GET http://localhost:5001/notes

###
GET http://localhost:5001/notes/1

###
POST  http://localhost:5001/notes
Content-Type: application/json

{
    "judul" : "FIKA",
    "content" : "taufika@gmail.com"
}

###
PATCH   http://localhost:5001/notes/1
Content-Type: application/json

{
    "judul" : "FIKAA",
    "content" : "taufika@gmail.com"
}

###
DELETE  http://localhost:5001/notes/11


GET http://localhost:5001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InRlcyIsImVtYWlsIjoidGVzQHRlcy5jb20iLCJnZW5kZXIiOiJNYWxlIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0wNFQxNzo0Nzo0OS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0wNFQxODoxMzoyOS4wMDBaIiwiaWF0IjoxNzQ2MzgyNjI4LCJleHAiOjE3NDYzODI2NTh9.7oXC7vpjl28v7ez0mO7sZGW1v33kLXo0HFkg5fcEyC0

###

POST http://localhost:5001/add-user 
Content-Type: application/json

{
    "name": "tes",
    "email": "tes@tes.com",
    "gender": "Male",
    "password": "12345"
}

### 

PUT http://localhost:5001/edit-user/14
Content-Type: application/json

{
    "name": "tessss",
    "email": "tesss@tessss.com",
    "gender": "Male"
}

###

DELETE http://localhost:5001/delete-user/17


###

POST http://localhost:5001/login
Content-Type: application/json

{
   
    "email": "tes@tes.com",
    "password": "12345"
}



###

DELETE http://localhost:5001/logout